name: urban-heat-ml
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - geopandas
  - folium
  - rasterio
  - rasterstats
  - shapely
  - fiona
  - pyproj
  - osmnx
  - requests
  - tqdm
  - xgboost
  - pip
  - pip:
      - earthpy
      - geopy
